#!/usr/bin/env python3
"""Build a softmod save: the broadcast shipped inside a save's scenario script.

A mod has to be installed by every client and matched by checksum, so clients
are prompted to sync it. A scenario script travels inside the save itself, so
joining clients need nothing at all.

    python3 scripts/make-scenario.py <source.zip> <output.zip> [--port 41234]

The source save's own control.lua is preserved and appended to, so whatever
scenario it already runs (freeplay, usually) keeps working.
"""
import argparse
import os
import sys
import zipfile

MARKER = "-- factorio-broadcast:softmod"

TEMPLATE = """
{marker} (generated by scripts/make-scenario.py - edit mod/broadcast.lua instead)
require('broadcast').setup(function()
  return {{
    enabled = true,
    port = {port},
    interval = {interval},
    rescan_seconds = {rescan},
    windows = '{windows}',
    history_items = {history_items},
    history_every = {history_every},
  }}
end)
"""


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("source")
    parser.add_argument("output")
    parser.add_argument("--port", type=int, default=41234)
    parser.add_argument("--interval", type=int, default=60)
    parser.add_argument("--rescan", type=int, default=300)
    parser.add_argument("--windows", default="5s,1m,10m,1h")
    parser.add_argument("--history-items", type=int, default=5)
    parser.add_argument("--history-every", type=int, default=5)
    args = parser.parse_args()

    here = os.path.dirname(os.path.abspath(__file__))
    logic_path = os.path.join(here, "..", "mod", "broadcast.lua")
    with open(logic_path, "r", encoding="utf-8") as handle:
        logic = handle.read()

    with zipfile.ZipFile(args.source) as source:
        names = source.namelist()
        if not names:
            print("empty save", file=sys.stderr)
            return 1
        root = names[0].split("/")[0]
        control_name = root + "/control.lua"
        if control_name not in names:
            print("no {} in save".format(control_name), file=sys.stderr)
            return 1

        control = source.read(control_name).decode("utf-8")
        if MARKER in control:
            # Rebuild from the part before the marker so this is idempotent.
            control = control.split(MARKER)[0].rstrip() + "\n"

        control += TEMPLATE.format(
            marker=MARKER,
            port=args.port,
            interval=args.interval,
            rescan=args.rescan,
            windows=args.windows,
            history_items=args.history_items,
            history_every=args.history_every,
        )

        if os.path.exists(args.output):
            os.remove(args.output)

        with zipfile.ZipFile(args.output, "w", zipfile.ZIP_DEFLATED) as out:
            for item in source.infolist():
                if item.filename == control_name:
                    out.writestr(item, control.encode("utf-8"))
                elif item.filename == root + "/broadcast.lua":
                    continue  # rewritten below
                else:
                    out.writestr(item, source.read(item.filename))
            out.writestr(root + "/broadcast.lua", logic.encode("utf-8"))

    print(
        "built {} ({} bytes) - scenario root '{}', udp port {}".format(
            args.output, os.path.getsize(args.output), root, args.port
        )
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
